-- fjerener alle tabeller og lager de på nytt
DROP TABLE IF EXISTS Ansatt;
DROP TABLE IF EXISTS Billett;
DROP TABLE IF EXISTS Sete;
DROP TABLE IF EXISTS TeaterSal;
DROP TABLE IF EXISTS TeaterOppsettning;
DROP TABLE IF EXISTS HarOppgave;
DROP TABLE IF EXISTS TeaterStykke;
DROP TABLE IF EXISTS Akt;
DROP TABLE IF EXISTS RolleIAkt;
DROP TABLE IF EXISTS HarRolle;
DROP TABLE IF EXISTS Rolle;
DROP TABLE IF EXISTS Skuespiller;
DROP TABLE IF EXISTS Direktor;
DROP TABLE IF EXISTS PrisTabell;
DROP TABLE IF EXISTS Ordre;
DROP TABLE IF EXISTS Kunde;
